;; Add hooks for prettify symbols mode
(add-hook 'prog-mode-hook 'prettify-symbols-mode)
(setq prettify-symbols-unprettify-at-point 'right-edge)

(add-hook 'coq-mode-hook
	  (lambda ()
            (mapc (lambda (pair) (push pair prettify-symbols-alist))
		  '(("forall". ?∀)
		    ("exists". ?∃)
		    ("~" . ?¬)
		    ("/\\" . ?⋀)
		    ("\\/" . ?⋁)
		    ("=>". ?⇒)
		    ("->". ?→)
		    ("<-" . ?←)
		    ("<->" . ?↔)
		    ("*" . ?×)))))

(setq tuareg-prettify-symbols-full t)

(add-hook 'fsharp-mode-hook
	  (lambda ()
	    (mapc (lambda (pair) (push pair prettify-symbols-alist))
		  '(("->". ?→)
		    ("sqrt" . ?√)
		    ("&&" . ?∧)
		    ("||" . ?∨)
		    ("*." . ?•)
		    ("/." . ?÷)
		    ("<=" . ?≤)
		    ("<-" . ?←)
		    (">=" . ?≥)
		    ("<>" . ?≠)
		    ("==" . ?≡)
		    ("<=>" . ?⇔)
		    ("=>" . ?⇒)
		    ("infinity" . ?∞)
		    ;; Some greek letters for type parameters.
		    ("'a" . ?α)
		    ("'b" . ?β)
		    ("'c" . ?γ)
		    ("'d" . ?δ)
		    ("'e" . ?ε)
		    ("'f" . ?φ)
		    ("'i" . ?ι)
		    ("'k" . ?κ)
		    ("'m" . ?µ)
		    ("'n" . ?ν)
		    ("'o" . ?ο)
		    ("'p" . ?π)
		    ("'r" . ?ρ)
		    ("'s" . ?σ)
		    ("'t" . ?τ)
		    ("'x" . ?ξ)
		    ;; Some sketchy ones that might make a mess of alignment
		    ("fun" . ?λ)
		    ("not" . ?¬)
		    ("[|" . ?〚) ;; 〚
		    ("|]" . ?〛) ;; 〛
		    ("->" . ?→)
		    (":=" . ?⇐)
		    ("fun" . ?λ)
		    ("not" . ?¬)
               	    ("->" . ?→)
		    (":=" . ?⇐)
		    ("let" . ?𝝘)
		    ("let!" . ?𝟊)
		    ("rec" . ?↺)
		    ("type" . ?𝔱)
		    ("module" . ?𝔐)
		    ("val" . ?𝔳)
		    ("::" . ?∷)
		    ("for" . ?∀)
		    ("|>" . ?▷)
		    ))))
